### ISSUE TITLE
Cannot open settings window on Windows 10

### ISSUE THREAD

**Issue by Solidogen** [Stinger21/imageDeCap#77]
I was successfully using imageDeCap for some time, but with new system installation can't setup image saving folder, because:
![issue](https://user-images.githubusercontent.com/20575586/29558713-408dccd6-872d-11e7-82c4-4e8516662478.png)

Looks like some GC issue, did you have any problems with this in the past?

**Comment by Stinger21** [comment]
Interesting. Thanks for contacting me :o

The screenshot you linked looks like the current version (1.23).
And not the most recent one (1.24) I tried writing my own "installer" in
1.23 that made a copy of the program in %appdata%/imageDeCap instead of
using an actual, normal installer.

The problem you are having should be fixable by going into the settings of
(1.23), clicking uninstall then closing the program and starting it up
again.

Ill make sure to have the new version delete the old one when it installs :)

**Comment by Solidogen** [comment]
Thanks, 1.24 gets me access to settings. I found bugs in gif mode, I'll share them
